[package]
name = "rustorium"
version = "0.1.0"
edition = "2021"
description = "A high-performance distributed ledger system written in Rust"
authors = ["OpenHands <openhands@all-hands.dev>"]

[dependencies]
# Sharding implementation
consistent_hash_ring = "0.8.0"
dashmap = "5.5.3"
tokio = { version = "1.36.0", features = ["full"] }
serde = { version = "1.0.197", features = ["derive"] }
rayon = "1.8.1"

# Avalanche-type gossip protocol
libp2p = { version = "0.53.2", features = ["gossipsub", "identify", "kad", "noise", "tcp", "yamux"] }
quinn = "0.10.2"
rand = "0.8.5"
blake3 = "1.5.0"
metrics = "0.21.1"

# Multi-VM execution environment
wasmer = "4.2.5"
once_cell = "1.19.0"

# Storage engine
# rocksdb = "0.21.0"  # 一時的に無効化
bincode = "1.3.3"
lz4 = "1.24.0"
parking_lot = "0.12.1"
priority-queue = "1.3.2"

# API/Web server
axum = "0.7.4"
tower-http = { version = "0.5.1", features = ["cors", "compression-full", "trace", "fs"] }
jsonwebtoken = "9.2.0"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }

# Web UI
yew = { version = "0.21.0", features = ["csr"] }
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
web-sys = { version = "0.3.69", features = ["HtmlInputElement", "Window", "Document", "Element", "HtmlElement", "console"] }
gloo-net = "0.5.0"
gloo-console = "0.3.0"
gloo-timers = "0.3.0"
serde_json = "1.0.114"

# AI processing layer
ndarray = "0.15.6"
reqwest = { version = "0.11.24", features = ["json"] }

# DAG-based parallel processing
petgraph = "0.6.4"
crossbeam = "0.8.4"
indexmap = "2.2.2"
flume = "0.11.0"

# Consensus engine
ed25519-dalek = "2.1.1"
reed-solomon-erasure = "4.0.2"
rand_chacha = "0.3.1"
# Remove c-kzg dependency by not using revm's default features
revm = { version = "3.5.0", default-features = false, features = ["std", "serde", "memory_limit"] }

# System integration
clap = { version = "4.5.1", features = ["derive"] }
config = "0.13.4"
anyhow = "1.0.79"
thiserror = "1.0.57"

# Testing and benchmarking
[dev-dependencies]
criterion = "0.5.1"
proptest = "1.4.0"
mockall = "0.12.1"
test-case = "3.3.1"
tokio-test = "0.4.3"

[[bench]]
name = "sharding_bench"
harness = false

[[bench]]
name = "storage_bench"
harness = false

[[bench]]
name = "consensus_bench"
harness = false
