[package]
name = "rustorium"
version = "0.1.0"
edition = "2021"
authors = ["OpenHands <openhands@all-hands.dev>"]
description = "Next-generation blockchain platform with geographic distribution"

[dependencies]
# Core
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
async-trait = "0.1"
futures = "0.3"

# Storage and Database
redb = "1.5"
rocksdb = { version = "0.20", features = ["multi-threaded-cf"], default-features = false }
bincode = "1.3"

# Network and P2P
quinn = { version = "0.10", features = ["rustls", "tls-rustls"] }
rustls = { version = "0.21", features = ["dangerous_configuration"] }
rcgen = "0.12"
tokio-rustls = "0.24"

# Consensus and Distributed Systems
raft = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Caching and Performance
dashmap = "5.5"
lru = "0.12"

# Monitoring and Metrics
prometheus = "0.13"
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# CLI and UI
clap = { version = "4.0", features = ["derive"] }
console = "0.15"
dialoguer = "0.11"
indicatif = "0.17"
colored = "2.0"
rustyline = "13.0"
atty = "0.2"
crossterm = "0.27"

# Web and API
axum = "0.7"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "fs"] }
hyper = { version = "1.0", features = ["full"] }
utoipa = { version = "4", features = ["axum_extras", "yaml"] }
utoipa-swagger-ui = { version = "5", features = ["axum"] }

# System and Utils
sys-info = "0.9"
webbrowser = "0.8"
rust-embed = "8.0"
mime_guess = "2.0"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.0", features = ["v4", "serde"] }
toml = "0.8"

# Zero Knowledge Proofs
poseidon-rs = "0.0.8"

# Testing
criterion = { version = "0.5", features = ["async_tokio"] }
rand = "0.8"

[features]
default = ["bundled-rocksdb"]
bundled-rocksdb = ["rocksdb/default"]  # rocksdbをバンドルする場合
system-rocksdb = []     # システムのrocksdbを使用する場合

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
rand = "0.8"
uuid = { version = "1.0", features = ["v4"] }

[[bench]]
name = "benchmark"
harness = false

[[bin]]
name = "rustorium"
path = "src/main.rs"
