[package]
name = "rustorium"
version = "0.1.0"
edition = "2021"
description = "Rustorium - A blockchain platform implemented in Rust"
authors = ["OpenHands <openhands@all-hands.dev>"]

[workspace]
members = [
    "api",
    "frontend",
]

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.dev.build-override]
opt-level = 0

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false

[profile.fast-dev]
inherits = "dev"
opt-level = 1
codegen-units = 128
incremental = true
debug = 0

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
anyhow = "1.0.79"
dialoguer = "0.11.0"
console = "0.15.8"
indicatif = "0.17.8"
colored = "2.1.0"
clap = { version = "4.5.1", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
chrono = { version = "0.4", features = ["serde"] }
reqwest = { version = "0.11", features = ["json"] }
tokio-util = "0.7"
futures = "0.3"
async-trait = "0.1"
thiserror = "1.0"
hex = "0.4"
sha2 = "0.10"
ed25519-dalek = "2.1"
rand = "0.8"
rustyline = "13.0"
prettytable-rs = "0.10"
termion = "3.0"
tui = "0.19"
crossterm = "0.27"
plotters = "0.3"
regex = "1.10"
walkdir = "2.4"
tempfile = "3.10"
zip = "0.6"
rayon = "1.8"
num_cpus = "1.16"
humantime = "2.1"
byte-unit = "5.1"
sysinfo = "0.30"
ctrlc = "3.4"
dirs = "5.0"
config = "0.14"
toml = "0.8"
log = "0.4"
env_logger = "0.11"
libp2p = { version = "0.53", features = ["tcp", "dns", "websocket", "noise", "yamux", "gossipsub", "mdns", "kad", "request-response", "identify", "ping", "metrics", "tokio"] }
libp2p-identity = { version = "0.2", features = ["rand"] }
libp2p-swarm = "0.44"
libp2p-swarm-derive = "0.44"
multiaddr = "0.18"
rocksdb = { version = "0.21", features = ["multi-threaded-cf"] }
bincode = "1.3"
snap = "1.1"
bytes = "1.5"

[[bin]]
name = "rustorium"
path = "src/main.rs"
