[package]
name = "rustorium"
version = "0.1.0"
edition = "2021"
description = "Rustorium - A blockchain platform implemented in Rust"
authors = ["OpenHands <openhands@all-hands.dev>"]

[workspace]
members = [
    "api",
    "web",
]

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
anyhow = "1.0.79"

[[bin]]
name = "rustorium"
path = "src/main.rs"
