[package]
name = "rustorium"
version = "0.1.0"
edition = "2021"
description = "Rustorium - A blockchain platform implemented in Rust"
authors = ["OpenHands <openhands@all-hands.dev>"]

[workspace]
members = [
    "api",
    "frontend",
]

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 256
rpath = false

[profile.dev.build-override]
opt-level = 0

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false

[profile.fast-dev]
inherits = "dev"
opt-level = 1
codegen-units = 128
incremental = true
debug = 0

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
anyhow = "1.0.79"

[[bin]]
name = "rustorium"
path = "src/main.rs"
