[package]
name = "web"
version = "0.1.0"
edition = "2021"
description = "Web server for Rustorium"
authors = ["OpenHands <openhands@all-hands.dev>"]

[dependencies]
axum = { version = "0.7.4", features = ["ws"] }
tokio = { version = "1.36.0", features = ["full"] }
tower-http = { version = "0.5.1", features = ["fs", "cors", "trace"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
anyhow = "1.0.79"
clap = { version = "4.5.32", features = ["derive"] }
serde_json = "1.0.140"
chrono = { version = "0.4.40", features = ["serde"] }
sha2 = "0.10.8"
uuid = { version = "1.16.0", features = ["v4", "serde"] }
serde = { version = "1.0.219", features = ["derive"] }
futures-util = "0.3.31"
tokio-tungstenite = "0.26.2"
