# Rustorium Configuration

[node]
id = "node-1"
data_dir = "./data"
log_level = "info"

[network]
listen_addr = "0.0.0.0"
listen_port = 30333
bootstrap_nodes = []
max_peers = 50
gossip_interval_ms = 1000
connection_timeout_ms = 5000

[storage]
db_path = "./data/db"
cache_size_mb = 512
max_open_files = 1000
compaction_style = "level"

[sharding]
shard_count = 4
rebalance_interval_sec = 3600
min_shard_size = 1000
max_shard_size = 1000000

[consensus]
algorithm = "avalanche"
block_time_ms = 2000
validators = []
min_validators = 4
threshold_percentage = 67

[api]
enabled = true
listen_addr = "0.0.0.0"
listen_port = 8080
cors_allowed_origins = ["*"]
rate_limit_requests = 100
rate_limit_period_sec = 60

[vm]
evm_enabled = true
move_vm_enabled = false
solana_vm_enabled = false
wasm_enabled = true
gas_limit = 10000000