[build]
rustc-wrapper = "sccache"
target-dir = "/tmp/cargo-target"

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-cpu=native"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "target-cpu=native"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-cpu=native"]

[profile.fast]
inherits = "release"
opt-level = 2
debug = false
strip = true
lto = "thin"
panic = "abort"
codegen-units = 256
incremental = true
