[package]
name = "rustorium-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
tonic = "0.10"
async-graphql = "6.0"

tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1"
